In [79]:
import pandas as pd
from tqdm import tqdm
tqdm.pandas()
ai_df = pd.read_csv("/home/aml7990/Code/creativity-item-generation/item_evaluation/Content Review/AllItemsToScore_rated.csv")
human_df = pd.read_csv("/home/aml7990/Code/creativity-item-generation/item_evaluation/Content Review/humanwrittenitemsrated.csv")

In [80]:
# drop unneeded columns
ai_df = ai_df[["creative_scenario_round_4", "Complexity_rater5", "Difficulty_rater5","Accessibility_rater5","Controversial_rater5","Word List Inclusion_rater5","Leading_rater5",
            "Difficulty_rater4","Accessibility_rater4","Controversial_rater4","Word List Inclusion_rater4","Leading_rater4", "Complexity_rater4",
            "Difficulty_rater3","Accessibility_rater3","Controversial_rater3","Word List Inclusion_rater3","Leading_rater3", "Complexity_rater3",
            "Difficulty_rater2","Accessibility_rater2","Controversial_rater2","Word List Inclusion_rater2","Leading_rater2", "Complexity_rater2",
            "Difficulty_rater1","Accessibility_rater1","Controversial_rater1","Word List Inclusion_rater1","Leading_rater1", "Complexity_rater1",
            "Difficulty_raterGA1","Accessibility_raterGA1","Controversial_raterGA1","Word List Inclusion_raterGA1","Leading_raterGA1", "Complexity_raterGA1",
            "Difficulty_raterGA2","Accessibility_raterGA2","Controversial_raterGA2","Word List Inclusion_raterGA2","Leading_raterGA2", "Complexity_raterGA2",
               ]
               ]

In [45]:
ai_df

,creative_scenario_round_4,Complexity_rater5,Difficulty_rater5,Accessibility_rater5,Controversial_rater5,Word List Inclusion_rater5,Leading_rater5,Difficulty_rater4,Accessibility_rater4,Controversial_rater4,...,Controversial_raterGA1,Word List Inclusion_raterGA1,Leading_raterGA1,Complexity_raterGA1,Difficulty_raterGA2,Accessibility_raterGA2,Controversial_raterGA2,Word List Inclusion_raterGA2,Leading_raterGA2,Complexity_raterGA2
0,Amy works at Lily's Cafe. She has been working...,1.0,3.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,...,0.0,1.0,0.0,2.0,NaN,NaN,NaN,1.0,NaN,NaN
1,Benjamin is a regular at Sophia's Cafe. He spe...,2.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,...,0.0,1.0,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
2,Olivia is a theater actress who has been prepa...,3.0,1.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,...,1.0,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
3,Daniel is a weightlifter who has been training...,2.0,3.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,...,0.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
4,Lucas is a college student who works part-time...,3.0,3.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,...,0.0,1.0,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
468,Oliver is a struggling actor who has been work...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,3.0,0.0,0.0,0.0,0.0,4.0
469,"Human: Word list: 1. Emma, ...",NaN,NaN,NaN,NaN,NaN,NaN,3.0,0.0,0.0,...,NaN,NaN,NaN,NaN,2.0,0.0,0.0,0.0,1.0,2.0
470,Scenario:Michael and Sophia are good friends w...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,2.0,0.0,0.0,1.0,0.0,1.0
471,Olivia is a barista at a popular coffee shop i...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,2.0
472,Human: Word list: 10. Elija...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,0.0,0.0,...,NaN,NaN,NaN,NaN,2.0,0.0,0.0,0.0,1.0,2.0

In [81]:
# clean df:
from math import floor
ai_df["complexity_aggregrate"] = -1
ai_df["difficulty_aggregrate"] = -1

for index, row in ai_df.iterrows():
    non_null_cols = row.dropna()
    # drop any non-acessible, leading, or controversial items (rated so by at least 1 ratrer)
    controverisal_ids = non_null_cols.index.str.contains("Controversial")
    if any(non_null_cols.loc[controverisal_ids]):
        # print("here")
        continue
    accessible_ids = non_null_cols.index.str.contains("Accessibility")
    if any(non_null_cols.loc[accessible_ids]):
        # print("here")
        continue
    leading_ids = non_null_cols.index.str.contains("Leading")
    if any(non_null_cols.loc[leading_ids]):
        # print("here")
        continue

    # compute the floor of the average complexity and difficulty
    complexity_ids = non_null_cols.index.str.contains("Complexity")
    complexity_agg = floor(non_null_cols.loc[complexity_ids].mean())
    ai_df.at[index, "complexity_aggregrate"] = complexity_agg
    
    difficulty_ids = non_null_cols.index.str.contains("Difficulty")
    difficulty_agg = floor(non_null_cols.loc[difficulty_ids].mean())
    ai_df.at[index, "difficulty_aggregrate"] = difficulty_agg
    # break

In [82]:
ai_df = ai_df[(ai_df["complexity_aggregrate"] != -1) | (ai_df["difficulty_aggregrate"] != -1)]

In [67]:
ai_df

,creative_scenario_round_4,Complexity_rater5,Difficulty_rater5,Accessibility_rater5,Controversial_rater5,Word List Inclusion_rater5,Leading_rater5,Difficulty_rater4,Accessibility_rater4,Controversial_rater4,...,Leading_raterGA1,Complexity_raterGA1,Difficulty_raterGA2,Accessibility_raterGA2,Controversial_raterGA2,Word List Inclusion_raterGA2,Leading_raterGA2,Complexity_raterGA2,complexity_aggregrate,difficulty_aggregrate
0,Amy works at Lily's Cafe. She has been working...,1.0,3.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,...,0.0,2.0,NaN,NaN,NaN,1.0,NaN,NaN,2,3
1,Benjamin is a regular at Sophia's Cafe. He spe...,2.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,...,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2,1
4,Lucas is a college student who works part-time...,3.0,3.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,...,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,3,2
7,Hannah is a high school student who spends a l...,2.0,2.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,...,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,3,2
11,Rachel is a fitness enthusiast who regularly g...,4.0,4.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,...,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
461,"Human: Word list: Michael, ...",NaN,NaN,NaN,NaN,NaN,NaN,3.0,0.0,0.0,...,NaN,NaN,2.0,0.0,NaN,NaN,NaN,2.0,2,2
466,Benjamin is a barista at a local cafe. He has ...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,0.0,...,NaN,NaN,1.0,0.0,0.0,0.0,0.0,1.0,1,2
467,Daniel is a surfing instructor at Beach City S...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,0.0,0.0,...,NaN,NaN,3.0,0.0,0.0,0.0,0.0,2.0,2,2
468,Oliver is a struggling actor who has been work...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,0.0,...,NaN,NaN,3.0,0.0,0.0,0.0,0.0,4.0,2,2
471,Olivia is a barista at a popular coffee shop i...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,0.0,...,NaN,NaN,1.0,0.0,0.0,0.0,0.0,2.0,2,1

In [83]:
mask = ai_df["creative_scenario_round_4"].str.contains("Human: Word list:")
mask = mask.loc[mask == True]

In [84]:
# drop items that don't follow correct format
ai_df = ai_df.drop(index=mask.index)

In [85]:
ai_df

,creative_scenario_round_4,Complexity_rater5,Difficulty_rater5,Accessibility_rater5,Controversial_rater5,Word List Inclusion_rater5,Leading_rater5,Difficulty_rater4,Accessibility_rater4,Controversial_rater4,...,Leading_raterGA1,Complexity_raterGA1,Difficulty_raterGA2,Accessibility_raterGA2,Controversial_raterGA2,Word List Inclusion_raterGA2,Leading_raterGA2,Complexity_raterGA2,complexity_aggregrate,difficulty_aggregrate
0,Amy works at Lily's Cafe. She has been working...,1.0,3.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,...,0.0,2.0,NaN,NaN,NaN,1.0,NaN,NaN,2,3
1,Benjamin is a regular at Sophia's Cafe. He spe...,2.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,...,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2,1
4,Lucas is a college student who works part-time...,3.0,3.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,...,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,3,2
7,Hannah is a high school student who spends a l...,2.0,2.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,...,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,3,2
11,Rachel is a fitness enthusiast who regularly g...,4.0,4.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,...,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
455,Jessica and Benjamin are siblings who are both...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,0.0,...,NaN,NaN,1.0,0.0,0.0,0.0,0.0,2.0,2,1
466,Benjamin is a barista at a local cafe. He has ...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,0.0,...,NaN,NaN,1.0,0.0,0.0,0.0,0.0,1.0,1,2
467,Daniel is a surfing instructor at Beach City S...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,0.0,0.0,...,NaN,NaN,3.0,0.0,0.0,0.0,0.0,2.0,2,2
468,Oliver is a struggling actor who has been work...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,0.0,...,NaN,NaN,3.0,0.0,0.0,0.0,0.0,4.0,2,2
471,Olivia is a barista at a popular coffee shop i...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,0.0,...,NaN,NaN,1.0,0.0,0.0,0.0,0.0,2.0,2,1

In [86]:
# drop extra columns
ai_df = ai_df[["creative_scenario_round_4", "complexity_aggregrate", "difficulty_aggregrate"]]

In [87]:
# as a first experiment, split into train and dev sets for ai_df, with human being the test set
from sklearn.model_selection import train_test_split
train_ai, test_ai = train_test_split(ai_df, test_size=0.5, random_state=1)

In [88]:
train_ai

,creative_scenario_round_4,complexity_aggregrate,difficulty_aggregrate
13,Noah is a high school student who loves to gar...,3,2
339,Amy is a barista at Lily's Cafe. She has been ...,2,2
0,Amy works at Lily's Cafe. She has been working...,2,3
347,Lucas has been working at the local bookstore ...,2,1
176,Hannah was working at the library when she not...,3,2
...,...,...,...
292,Megan has been dating Tyler for six months and...,4,2
296,Grace has been working at the bakery for five ...,3,3
161,Olivia is a college student who works part-tim...,3,2
300,Benjamin has been working at the Cafe on Main ...,2,2
98,Grace is a talented baker who owns a small bak...,3,3

In [90]:
train_ai.to_csv("/home/aml7990/Code/creativity-item-generation/item_evaluation/cleaned_datasets/CPS_train.csv", index=False)
test_ai.to_csv("/home/aml7990/Code/creativity-item-generation/item_evaluation/cleaned_datasets/CPS_test.csv", index=False)